### ISSUE TITLE
Test tests_sanity_repository.yml can not access a repository on bintray (RHEL-8 host)

### ISSUE THREAD

**Issue by kurik** [performancecopilot/ansible-pcp#14]
I am trying to run ```tests_sanity_repository.yml``` on a target host with RHEL-8.4 and I am getting the following error:

```
TASK [performancecopilot.metrics.pcp : Install Performance Co-Pilot packages] *************************
fatal: [10.89.0.19]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'bintray-pcp-el8': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
```

Checking the baseurl ```https://dl.bintray.com/pcp/el8``` (taken from ```/etc/yum.repos.d/bintray-pcp.repo``` repofile) I am getting HTTP error code 403 - Forbidden.

If I am not mistaken, the PCP repository of releases has been moved from Bintray to Artifactory.

**Comment by andreasgerstmayr** [comment]
> If I am not mistaken, the PCP repository of releases has been moved from Bintray to Artifactory.

Yep, the latest releases are on JFrog Artifactory. Instructions on how to setup the repository are here: https://pcp.readthedocs.io/en/latest/HowTos/installation/index.html
