### ISSUE TITLE
Question: if additional PMDAs are used, how are the pmloggers (local and remote) updated to fetch them?

### ISSUE THREAD

**Issue by portante** [performancecopilot/ansible-pcp#25]
Question: if additional PMDAs are used, how are the pmloggers (local and remote) updated to fetch them?

I am not sure how that is updated.

**Comment by natoscott** [comment]
When every pmlogger service starts (or restarts, which is at least once a day) it will check the header of the pmlogger configuration file.  If this states the configuration was generated by pmlogconf, it will re-run the pmlogconf utility to see if the configuration has changed.  The presence of new PMDAs is handled at this time - if pmlogconf has a configuration template for those new metrics, and the metrics inclusion condition therein is met, the pmlogger configuration for that host will be updated to reflect the new (or removed) metrics before the pmlogger process is started by the pmlogger service.

**Comment by portante** [comment]
But, how do I know ahead of time if a given PMDA has a configuration template for it?

**Comment by natoscott** [comment]
Usual process is the PMDA author also supplies appropriate pmlogconf files, since they know the metrics best.  Alternatively, folks sometimes provide their own if that's missing - but best case is for us to supply 'em with PCP itself, for everyone to enjoy.

**Comment by portante** [comment]
Could we get some help on how to determine when we have enabled a PMDA but not metrics from it are being collected by the various pmloggers?

Ideally, I'd like to have a list of agents to be enabled, and then have the `pcp` role flag an error saying, "Hey buddy, you are adding PMDAs but no metrics for them will be configured in the pmloggers."

**Comment by natoscott** [comment]
Might be easier for us to tackle it at the source - perhaps we could add a PCP QA test that checks at least one pmlogconf file exists for every PMDA?  There may need to be some exceptions (unusual PMDAs like pmdabash for example), in which case we can filter those out in the test.
