### ISSUE TITLE
Eliminate non-inclusive language

### ISSUE THREAD

**Issue by nhosoi** [performancecopilot/ansible-pcp#42]
Hello, we have a project to eliminate non-inclusive language from the Linux-system-roles. Since the ansible-pcp role is vendored in the metrics role, we are hoping to clean up this role, as well. 

Running a utility woke (now it's supported in tox. please install the latest tox-lsr and run tox -e woke), two non-inclusive words are reported - `master` and `whitelist`.

Do you think they can be replaced with inclusive words? Or they are hardcoded in the subsystem? If the latter, we have to tell `woke` to skip the problematic word by adding `wokeignore:rule=master` or `wokeignore:rule=whitelist` individually...

**Comment by nhosoi** [comment]
I've opened https://github.com/performancecopilot/ansible-pcp/pull/44.
@natoscott, @richm, could you please take a look? Thanks!

**Comment by natoscott** [comment]
@noriko - thanks for working on this, I've added some comments to the PR

**Comment by nhosoi** [comment]
@natoscott, thank you for your discussions! Now we can close this issue, too.
